### PR TITLE
console log in new branch

### PR DESCRIPTION
**Pull request by petteri-te**
adding another console.log

### CODE REVIEW

**Comment by petteri-te** [comment]
👍

**Review by petteri-te — COMMENTED** [review]
👍 
looks good to me LGTM

**Review by petteri-te — COMMENTED** [review]
very good

**Review by petsQ — APPROVED** [review]
👍 
I approve
loooks good to me -- LGTM

**Review by petsQ — APPROVED** [review]
yes

**Review by petsQ — APPROVED** [review]

**Review by petsQ — APPROVED** [review]
i apporve again

**Pull request merged**
