### PR TITLE
added client side validation for not adding empty data to database

### PR DESCRIPTION
**Pull request by farsanau**

### CODE REVIEW

**Comment by BaheYaich** [comment]
Client-side form validation can be done using the attribute required for example. This is achievable without JS.

**Comment by MarcMcBurney** [comment]
This implementation will ensure compatibility with older browsers that may not support an HTML5 attribute approach

**Comment by farsanau** [comment]
Changed the client side validation with html attribute

**Review by MarcMcBurney — APPROVED** [review]
Improvement to the form validation

**Comment by MarcMcBurney** [comment]
Farsana  PR that improves form validation to ensure all fields are filled out before submission.

**Pull request merged**
